config/routes.rb
Rails.application.routes.draw do
  resources :ads, except: :show
  
  post 'tablets' => 'tablets#create'

  post 'tablets/:tablet_id/location' => 'tablets#update_location'

  post 'users' => 'users#create'

  get 'users/:user_id/tablets' => 'tablets#user_tablets'
  post 'users/:user_id/tablets' => 'users#associate_tablet'
  delete 'users/:user_id/tablets' => 'users#disassociate_tablet'

  root 'ads#index'

end

app/models/ad.rb
class Ad < ActiveRecord::Base
	validates_format_of :destination_url, :with => URI::regexp(%w(http https))
	validates_format_of :picture_url, :with => URI::regexp(%w(http https))
	validates :description, length: { maximum: 80 }
end

app/controllers/ads_controller.rb
class AdsController < SecurityController
  before_action :set_ad, only: [:show, :edit, :update, :destroy]
  skip_before_filter :authenticate_tablet!

  # GET /ads
  # GET /ads.json
  def index
    @ads = Ad.all
    respond_to do |format|
      format.html { render :index }
      if (@ads.count == 0)
        format.json { Array.new }
      else
        format.json { @ads }
      end
    end
  end

  # GET /ads/1
  # GET /ads/1.json
  def show
    render :edit
  end

  # GET /ads/new
  def new
    @ad = Ad.new
  end

  # GET /ads/1/edit
  def edit
  end

  # POST /ads
  # POST /ads.json
  def create
    @ad = Ad.new(ad_params)

    respond_to do |format|
      if @ad.save
        format.html { redirect_to action: :index, notice: 'Ad was successfully created.' }
        format.json { render :index, status: :created }
      else
        format.html { render :new }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ads/1
  # PATCH/PUT /ads/1.json
  def update
    respond_to do |format|
      if @ad.update(ad_params)
        format.html { redirect_to action: :index, notice: 'Ad was successfully updated.' }
        format.json { render :index, status: :ok, location: @ad }
      else
        format.html { render :edit }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ads/1
  # DELETE /ads/1.json
  def destroy
    @ad.destroy
    respond_to do |format|
      format.html { redirect_to ads_url, notice: 'Ad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ad
      @ad = Ad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ad_params
      params.require(:ad).permit(:picture_url, :destination_url, :description)
    end
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/views/ads/_form.html.erb
<%= form_for(@ad) do |f| %>
  <% if @ad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ad.errors.count, "error") %> prohibited this ad from being saved:</h2>

      <ul>
      <% @ad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-container">
    <div class="inline-fields">
      <div class="picture-url-field">
        <strong class="field-number">1- </strong> <%= f.label :picture_url %><br>
        <%= f.text_field :picture_url, class: 'text-field' %>
      </div>
      <div class="destination-url-field">
        <strong class="field-number">2- </strong> <%= f.label :destination_url %><br>
        <%= f.text_field :destination_url, class: 'text-field' %>
      </div>
    </div>
    <br>
    <div class="field">
      <strong class="field-number">3- </strong> <%= f.label :description %><br>
      <%= f.text_area :description, class: 'text-area' %>
    </div>
    <% if action_name != 'show'%>
      <div class="actions">
        <%= f.submit "#{action_name.capitalize} ad", :class => 'submit-btn' %>
      </div>
    <%end%>
  </div>
<% end %>

app/views/ads/edit.html.erb
<div class="container">
	<h1 class="title">Editing ad</h1>

	<%= render 'form' %>

	<%= link_to 'Back', ads_path %>
</div>

app/views/ads/index.html.erb
<div class="container">
  <h1 class="title">Listing ads</h1>

  <table class="ads-table">
    <thead class="ads-thead">
      <tr>
        <th>Preview</th>
        <th>Picture url</th>
        <th>Destination url</th>
        <th>Description</th>
        <th colspan="2"> Actions</th>
      </tr>
    </thead>

    <tbody class="ads-tbody">
      <% @ads.each do |ad| %>
        <tr>
          <td><img src="<%= ad.picture_url %>" class="ads-preview" /></td>
          <td><%= ad.picture_url %></td>
          <td><%= ad.destination_url %></td>
          <td><%= ad.description %></td>
          <td><%= link_to 'Edit', edit_ad_path(ad) %></td>
          <td><%= link_to 'Destroy', ad, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <%= link_to "<button class='submit-btn'>New Ad</button>".html_safe, new_ad_path %>
</div>
<br>

app/views/ads/new.html.erb
<div class="container">
	<h1 class="title">New add</h1>

	<%= render 'form' %>

	<%= link_to 'Back', ads_path %>
</div>

app/views/ads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Picture url:</strong>
  <%= @ad.picture_url %>
</p>

<p>
  <strong>Destination url:</strong>
  <%= @ad.destination_url %>
</p>

<p>
  <strong>Description:</strong>
  <%= @ad.description %>
</p>

<%= link_to 'Edit', edit_ad_path(@ad) %> |
<%= link_to 'Back', ads_path %>