config/routes.rb
Rails.application.routes.draw do
  resources :ads, except: :show
  
  post 'tablets' => 'tablets#create'

  post 'tablets/:tablet_id/location' => 'tablets#update_location'

  post 'users' => 'users#create'

  get 'users/:user_id/tablets' => 'tablets#user_tablets'
  post 'users/:user_id/tablets' => 'users#associate_tablet'
  delete 'users/:user_id/tablets' => 'users#disassociate_tablet'

  root 'ads#index'

end

app/models/tablet.rb
require 'digest/sha1'

class Tablet < ActiveRecord::Base
  has_many :locations
  belongs_to :user

  validates :uuid, presence: true, uniqueness: true

  def self.salt_that_token(unsalted_token, salt)
		return Digest::SHA1.hexdigest([unsalted_token, salt].join('')).to_s # "2aba83b05dc9c2d9db7e5d34e69787d0a5e28fc5"
  end

  def self.generate_secret(a, b) #, c)
		secret_token = 'zapallitos'
    joined_str = [a,b,secret_token].join('/')
    OpenSSL::Digest::SHA256.new(joined_str.encode('UTF-8'))
  end

end

app/controllers/tablets_controller.rb
require 'securerandom'

class TabletsController < SecurityController
  before_action :set_tablet, only: [:show]

  skip_before_action :authenticate_request!, only: [:create]
  before_action :authenticate_create!, only: [:create]

  # GET /tablets
  # GET /tablets.json
  def index
    @tablets = Tablet.all
  end

  # GET /tablets/1
  # GET /tablets/1.json
  def show
  end

  # POST /tablets
  # POST /tablets.json
  def create
    salt = SecureRandom.base64
    token = Tablet.salt_that_token(tablet_params[:flash_token], salt)

    @tablet = Tablet.find_by(uuid: tablet_params[:uuid])
    @tablet ||= Tablet.new(tablet_params)

    @tablet.update(flash_token: token)
    @tablet.update(salt: salt)

    respond_to do |format|
      if @tablet.save
        format.json { render json: { tablet_id: @tablet.id, flash_token: @tablet.flash_token }, status: :ok }
      else
        format.json { render json: @tablet.errors, status: :unprocessable_entity }
      end
    end
  end

  def user_tablets
    respond_to do |format|
      if current_user.tablets.count == 0
        format.json { render json: Array.new }
      else
        tablets_with_location = Array.new
        current_user.tablets.each do |t|
          if t.locations
            tablets_with_location.push t
          end
        end
        format.json { render json: tablets_with_location.to_json(:include => :locations) }
      end
    end
  end

  def update_location
    loc = Location.create(tablet_params[:location])
    current_tablet.locations << loc
    
    respond_to do |format|
      if current_tablet.save
        format.json { render json: "Ok", status: :ok }
      else
        format.json { render json: current_tablet.errors, status: :unprocessable_entity }
      end
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tablet
      @tablet = Tablet.find(params[:tablet_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tablet_params
      params.require(:tablet).permit(:uuid, :flash_token, :salt, :flash_date, :user_id, :location => [:latitude, :longitude, :altitude, :speed, :accuracy, :is_gps_provider, :date])
    end
end

app/helpers/tablets_helper.rb
module TabletsHelper
end

app/views/tablets/_form.html.erb
<%= form_for(@tablet) do |f| %>
  <% if @tablet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tablet.errors.count, "error") %> prohibited this tablet from being saved:</h2>

      <ul>
      <% @tablet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uuid %><br>
    <%= f.text_field :uuid %>
  </div>
  <div class="field">
    <%= f.label :flash_token %><br>
    <%= f.text_field :flash_token %>
  </div>
  <div class="field">
    <%= f.label :salt %><br>
    <%= f.text_field :salt %>
  </div>
  <div class="field">
    <%= f.label :flash_date %><br>
    <%= f.datetime_select :flash_date %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tablets/edit.html.erb
<h1>Editing tablet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tablet %> |
<%= link_to 'Back', tablets_path %>

app/views/tablets/index.html.erb
<h1>Listing tablets</h1>

<table>
  <thead>
    <tr>
      <th>Uuid</th>
      <th>Flash token</th>
      <th>Salt</th>
      <th>Flash date</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tablets.each do |tablet| %>
      <tr>
        <td><%= tablet.uuid %></td>
        <td><%= tablet.flash_token %></td>
        <td><%= tablet.salt %></td>
        <td><%= tablet.flash_date %></td>
        <td><%= tablet.user %></td>
        <td><%= link_to 'Show', tablet %></td>
        <td><%= link_to 'Edit', edit_tablet_path(tablet) %></td>
        <td><%= link_to 'Destroy', tablet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tablet', new_tablet_path %>

app/views/tablets/new.html.erb
<h1>New tablet</h1>

<%= render 'form' %>

<%= link_to 'Back', tablets_path %>

app/views/tablets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Uuid:</strong>
  <%= @tablet.uuid %>
</p>

<p>
  <strong>Flash token:</strong>
  <%= @tablet.flash_token %>
</p>

<p>
  <strong>Salt:</strong>
  <%= @tablet.salt %>
</p>

<p>
  <strong>Flash date:</strong>
  <%= @tablet.flash_date %>
</p>

<p>
  <strong>User:</strong>
  <%= @tablet.user %>
</p>

<%= link_to 'Edit', edit_tablet_path(@tablet) %> |
<%= link_to 'Back', tablets_path %>